### ISSUE TITLE
Core functionality tracker

### ISSUE THREAD

**Issue by rannie-peralta** [rannie-peralta/element-light-box#11]
### Features:

- [ ] Addons
- [ ] Hooks
- [ ] SCSS variable bindings

### Element lightening phases (in order)

- [ ] Resolving target element
- [ ] Positioning of target element
- [ ] Disabling of target element ancestors siblings
